defmodule Mach10.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :reference, :text, null: false
      add :avatar_url, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :organization_id, :bigserial
    end

    create table(:tracks, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :reference, :text, null: false
      add :header_img_url, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :organization_id, :bigserial
    end

    create table(:records, primary_key: false) do
      add :time_ms, :bigint, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :organization_id, :bigserial
      add :track_id, :bigserial, null: false, primary_key: true
      add :user_id, :bigserial, null: false, primary_key: true
    end

    create table(:organizations, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:users) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               prefix: "public",
               name: "users_organization_id_fkey",
               type: :bigserial
             )
    end

    alter table(:tracks) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               prefix: "public",
               name: "tracks_organization_id_fkey",
               type: :bigserial
             )
    end

    alter table(:records) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               prefix: "public",
               name: "records_organization_id_fkey",
               type: :bigserial
             )
    end

    alter table(:records) do
      modify :track_id,
             references(:tracks,
               column: :id,
               prefix: "public",
               name: "records_track_id_fkey",
               type: :bigserial
             )
    end

    alter table(:records) do
      modify :user_id,
             references(:users,
               column: :id,
               prefix: "public",
               name: "records_user_id_fkey",
               type: :bigserial
             )
    end

    alter table(:organizations) do
      add :reference, :text, null: false
      add :name, :text, null: false
      add :logo_url, :text
      add :header_img_url, :text
      add :description, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:history, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :time_ms, :bigint, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "history_organization_id_fkey",
            type: :bigserial,
            prefix: "public"
          )

      add :track_id,
          references(:tracks,
            column: :id,
            name: "history_track_id_fkey",
            type: :bigserial,
            prefix: "public"
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "history_user_id_fkey",
            type: :bigserial,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:history, "history_user_id_fkey")

    drop constraint(:history, "history_track_id_fkey")

    drop constraint(:history, "history_organization_id_fkey")

    drop table(:history)

    alter table(:organizations) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :header_img_url
      remove :logo_url
      remove :name
      remove :reference
    end

    drop constraint(:records, "records_user_id_fkey")

    alter table(:records) do
      modify :user_id, :bigserial
    end

    drop constraint(:records, "records_track_id_fkey")

    alter table(:records) do
      modify :track_id, :bigserial
    end

    drop constraint(:records, "records_organization_id_fkey")

    alter table(:records) do
      modify :organization_id, :bigserial
    end

    drop constraint(:tracks, "tracks_organization_id_fkey")

    alter table(:tracks) do
      modify :organization_id, :bigserial
    end

    drop constraint(:users, "users_organization_id_fkey")

    alter table(:users) do
      modify :organization_id, :bigserial
    end

    drop table(:organizations)

    drop table(:records)

    drop table(:tracks)

    drop table(:users)
  end
end
